dist: trusty
sudo: required
language: node_js

# Caches lets Travis CI store directories between builds,
# which is useful for storing dependencies that take
# longer to compile or download.
cache:
  directories:
    - "node_modules"

git:
  # Travis CI clones repositories to a depth of X commits.
  depth: 5

addons:
  chrome: stable

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome-stable
  # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - npm install

script:
  - npm run lint
  - npm run test:ci
